apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  instances: 1
  storage:
    size: 1Gi
