ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443
  postgres:
    port: 5432
    expose:
      default: true
    exposedPort: 5432
    protocol: TCP
    nodePort: 30432
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.baas.wke.csie.ncnu.edu.tw`)
    tls:
      secretName: wildcard-baas-tls
logs:
  access:
    enabled: true
